    name: Push CI
    on: [push]
    
    jobs:
      build_and_test:
        name: Build, Test, and Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
        steps:
          # Check out current commit
          - name: Checkout
    	uses: actions/checkout@v2
    
          # Make sure buildkit is enabled
          - name: Enable buildkit
    	shell: bash
    	run: |
    	  echo '{"experimental": "enabled"}' > ~/.docker/config.json
    
          # Build and run the static environment
          - name: Build Static
    	run: make static-docker-compose.yml
    
          # Log in to Docker, if we have the secrets
          - name: Docker Login
    	uses: docker/login-action@v1
    	with:
    	  registry: ghcr.io
    	  username: ${{ env.DOCKER_USER }}
    	  password: ${{ secrets.DOCKER_PASS }}
    
          # Push docker images
          - name: Docker Push
    	run: docker-compose push drupal
